version: '3'
services:
  frontend:
    build:
      context: ./url-shortener-frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    restart: unless-stopped
    volumes:
      - ./url-shortener-frontend/src/:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start
  backend:
    build:
      context: ./url-shortener-backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    restart: unless-stopped
    volumes:
      - ./url-shortener-backend/src/:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: npm run start:dev
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
